/* ═══════════════════════════════════════════════════
   SettingsContext — глобальные настройки пользователя

   Тёмная тема, язык, размер шрифта, компактный режим.
   Сохраняется в localStorage для персистентности.
   ═══════════════════════════════════════════════════ */

import { createContext, useContext, useState, useEffect } from 'react'

const SettingsContext = createContext(null)

export function useSettings() {
  const ctx = useContext(SettingsContext)
  if (!ctx) throw new Error('useSettings должен быть внутри SettingsProvider')
  return ctx
}

const TRANSLATIONS = {
  ru: {
    // ── Навигация ──
    'nav.home': 'Главная',
    'nav.materials': 'Материалы',
    'nav.teachers': 'Преподаватели',
    'nav.login': 'Войти',
    'nav.register': 'Регистрация',
    'nav.dashboard': 'Личный кабинет',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    // ── Главная страница ──
    'home.heroTitle1': 'Всё для учёбы —',
    'home.heroTitle2': 'в одном месте',
    'home.heroSubtitle': 'Рейтинги преподавателей, учебные материалы и личный кабинет — всё в одном портале для студентов и преподавателей',
    'home.heroBtn': 'Войти в портал',
    'home.learnMore': 'Узнать больше',
    'home.featuresTitle': 'Возможности портала',
    'home.featuresSubtitle': 'EduHub объединяет всё необходимое для учёбы и преподавания',
    'home.materialsTitle': 'Новые материалы',
    'home.materialsAll': 'Смотреть все',
    'home.ctaTitle': 'Присоединяйтесь к EduHub',
    'home.ctaDesc': 'Создайте аккаунт и получите доступ к рейтингам преподавателей, учебным материалам и персональному кабинету',
    'home.ctaRegister': 'Зарегистрироваться',
    'home.ctaTeachers': 'Преподаватели',
    // Статистика на главной
    'stat.students': 'Студентов',
    'stat.teachers': 'Преподавателей',
    'stat.materials': 'Материалов',
    'stat.ratings': 'Оценок',
    // Возможности
    'feat.materials': 'Учебные материалы',
    'feat.materialsDesc': 'Методички, лекции и справки — всегда под рукой',
    'feat.rating': 'Рейтинг преподавателей',
    'feat.ratingDesc': 'Честные оценки от студентов по прозрачным критериям',
    'feat.profile': 'Личный кабинет',
    'feat.profileDesc': 'Ваш профиль, закладки и история оценок',
    'feat.moderation': 'Надёжная модерация',
    'feat.moderationDesc': 'Все отзывы проходят проверку перед публикацией',
    // ── Страница преподавателей ──
    'teachers.title': 'Преподаватели',
    'teachers.subtitle': 'Рейтинги и профили преподавателей университета',
    'teachers.search': 'Поиск по имени или дисциплине...',
    'teachers.empty': 'Преподаватели не найдены',
    'teachers.emptyHint': 'Попробуйте изменить фильтры или очистить поиск',
    // Типы преподавателей (фильтры)
    'type.all': 'Все',
    'type.lecturer': 'Лекторы',
    'type.practice': 'Практики',
    'type.seminar': 'Семинары',
    'type.supervisor': 'Науч. рук.',
    'type.universal': 'Универсальные',
    // Типы (для бейджей в карточках)
    'typeBadge.lecturer': 'Лектор',
    'typeBadge.practice': 'Практик',
    'typeBadge.seminar': 'Семинарист',
    'typeBadge.supervisor': 'Науч. руководитель',
    'typeBadge.universal': 'Универсальный',
    // ── Профиль преподавателя ──
    'tp.about': 'Об авторе',
    'tp.criteria': 'Оценки по критериям',
    'tp.materials': 'Материалы',
    'tp.reviews': 'Отзывы',
    'tp.bio': 'О себе',
    'tp.disciplines': 'Преподаваемые дисциплины',
    'tp.contacts': 'Контакты',
    'tp.noInfo': 'Преподаватель пока не заполнил информацию о себе',
    'tp.rateBtn': 'Оценить преподавателя',
    'tp.alreadyRated': 'Вы уже оценили этого преподавателя',
    'tp.noRatings': 'Пока нет одобренных оценок',
    'tp.noMaterials': 'Преподаватель пока не загрузил материалы',
    'tp.noReviews': 'Пока нет одобренных отзывов',
    'tp.criteriaAvg': 'Средние оценки по критериям',
    'tp.notFound': 'Преподаватель не найден',
    'tp.ratingBased': 'на основе',
    'tp.ratingCount1': 'оценки',
    'tp.ratingCountN': 'оценок',
    'tp.studentYear': 'Студент',
    'tp.course': 'курса',
    // ── Материалы ──
    'mat.title': 'Учебные материалы',
    'mat.subtitle': 'Методички, лекции, задания и другие файлы для учёбы',
    'mat.upload': 'Загрузить',
    'mat.search': 'Поиск по названию или дисциплине...',
    'mat.allCategories': 'Все категории',
    'mat.allDisciplines': 'Все дисциплины',
    'mat.sortNewest': 'Новые сначала',
    'mat.sortAlphabet': 'По алфавиту',
    'mat.sortPopular': 'По популярности',
    'mat.empty': 'Материалы не найдены',
    'mat.emptyHint': 'Попробуйте изменить фильтры или очистить поиск',
    'mat.resetFilters': 'Сбросить фильтры',
    'mat.loadMore': 'Загрузить ещё',
    // Категории материалов
    'cat.all': 'Все категории',
    'cat.methodical': 'Методичка',
    'cat.lecture': 'Лекция',
    'cat.reference': 'Справка',
    'cat.assignment': 'Задание',
    'cat.other': 'Прочее',
    // Курсы
    'course.all': 'Все курсы',
    'course.1': '1 курс',
    'course.2': '2 курс',
    'course.3': '3 курс',
    'course.4': '4 курс',
    'course.common': 'Общие',
    // ── Кабинет преподавателя ──
    'td.myMaterials': 'Мои материалы',
    'td.ratings': 'Оценки и отзывы',
    'td.uploadBtn': 'Загрузить материал',
    'td.uploadFirst': 'Загрузить первый материал',
    'td.noMaterials': 'Вы пока не загрузили ни одного материала',
    'td.downloads': 'скачиваний',
    'td.ratingsToggleTitle': 'Разрешить студентам оценивать',
    'td.ratingsOnDesc': 'Студенты могут оставлять оценки и отзывы',
    'td.ratingsOffDesc': 'Оценивание отключено — студенты не могут оставлять оценки',
    'td.ratingsOn': 'Оценивание включено',
    'td.ratingsOff': 'Оценивание выключено',
    'td.avgCriteria': 'Средние оценки по критериям',
    'td.approved': 'Одобренных',
    'td.pending': 'На модерации',
    'td.rejected': 'Отклонённых',
    'td.studentReviews': 'Отзывы студентов',
    'td.noReviews': 'Пока нет одобренных отзывов',
    'td.statMaterials': 'Материалов',
    'td.statRatings': 'Оценок',
    'td.statAvg': 'Средний балл',
    'td.studentYear': 'курса',
    'td.studentPrefix': 'Студент',
    // ── Профиль студента ──
    'sp.myRatings': 'Мои оценки',
    'sp.bookmarks': 'Закладки',
    'sp.noRatings': 'Вы пока не оценивали преподавателей',
    'sp.noBookmarks': 'У вас пока нет сохранённых материалов',
    'sp.statusPending': 'На модерации',
    'sp.statusApproved': 'Одобрена',
    'sp.statusRejected': 'Отклонена',
    'sp.statRatings': 'Оценок',
    'sp.statBookmarks': 'Закладок',
    'sp.role': 'Студент',
    // ── Настройки — разделы ──
    'settings.title': 'Настройки',
    'settings.profile': 'Профиль',
    'settings.appearance': 'Оформление',
    'settings.notifications': 'Уведомления',
    'settings.privacy': 'Приватность',
    'settings.ratings': 'Оценки',
    'settings.security': 'Безопасность',
    'settings.account': 'Аккаунт',
    // Профиль
    'settings.avatar': 'Аватар',
    'settings.avatarChange': 'Изменить аватар',
    'settings.avatarRemove': 'Удалить',
    'settings.firstName': 'Имя',
    'settings.lastName': 'Фамилия',
    'settings.middleName': 'Отчество',
    'settings.email': 'Email',
    'settings.phone': 'Телефон',
    'settings.bio': 'О себе',
    'settings.socialLinks': 'Социальные сети',
    'settings.vk': 'ВКонтакте (ссылка)',
    'settings.telegram': 'Telegram (username)',
    'settings.save': 'Сохранить изменения',
    'settings.saving': 'Сохранение...',
    // Профиль — студент
    'settings.course': 'Курс',
    'settings.specialty': 'Специальность / Направление',
    'settings.group': 'Учебная группа',
    'settings.interests': 'Интересы',
    'settings.goals': 'Цели обучения',
    // Профиль — преподаватель
    'settings.contactEmail': 'Контактный email',
    'settings.degree': 'Учёная степень',
    'settings.academicTitle': 'Учёное звание',
    'settings.department': 'Кафедра',
    'settings.experience': 'Стаж работы (лет)',
    'settings.researchInterests': 'Научные интересы',
    'settings.office': 'Номер кабинета',
    'settings.officeHours': 'Часы приёма',
    'settings.website': 'Личный сайт',
    'settings.degreeNone': 'Без степени',
    'settings.degreeCandidate': 'Кандидат наук',
    'settings.degreeDoctor': 'Доктор наук',
    'settings.titleNone': 'Без звания',
    'settings.titleAssistant': 'Ассистент',
    'settings.titleDocent': 'Доцент',
    'settings.titleProfessor': 'Профессор',
    // Оформление
    'settings.theme': 'Тема оформления',
    'settings.themeLight': 'Светлая',
    'settings.themeDark': 'Тёмная',
    'settings.themeSystem': 'Системная',
    'settings.language': 'Язык интерфейса',
    'settings.fontSize': 'Размер текста',
    'settings.fontSizeNormal': 'Обычный',
    'settings.fontSizeLarge': 'Большой',
    'settings.fontSizeXLarge': 'Очень большой',
    'settings.compactMode': 'Компактный режим',
    'settings.compactModeDesc': 'Уменьшить отступы и размеры элементов для плотного отображения',
    'settings.cardStyle': 'Стиль карточек',
    'settings.cardStyleElevated': 'Объёмные',
    'settings.cardStyleFlat': 'Плоские',
    'settings.cardStyleOutlined': 'Контурные',
    // Уведомления
    'settings.notifEmail': 'Email-уведомления',
    'settings.notifEmailDesc': 'Получать письма о новых оценках и материалах',
    'settings.notifRatings': 'Новые оценки',
    'settings.notifRatingsDesc': 'Уведомлять, когда студент оценил вас',
    'settings.notifMaterials': 'Новые материалы',
    'settings.notifMaterialsDesc': 'Уведомлять о новых загруженных материалах',
    'settings.notifMessages': 'Сообщения',
    'settings.notifMessagesDesc': 'Уведомления о новых входящих сообщениях',
    'settings.notifAnnouncements': 'Объявления',
    'settings.notifAnnouncementsDesc': 'Важные новости и обновления портала',
    'settings.notifDigest': 'Еженедельный дайджест',
    'settings.notifDigestDesc': 'Сводка событий за прошедшую неделю',
    // Приватность
    'settings.profilePublic': 'Публичный профиль',
    'settings.profilePublicDesc': 'Другие пользователи могут видеть ваш профиль',
    'settings.showEmail': 'Показывать email',
    'settings.showEmailDesc': 'Отображать email в публичном профиле',
    'settings.showPhone': 'Показывать телефон',
    'settings.showPhoneDesc': 'Отображать телефон в публичном профиле',
    'settings.showSocialLinks': 'Показывать соцсети',
    'settings.showSocialLinksDesc': 'Отображать ссылки на ВКонтакте и Telegram',
    'settings.showStats': 'Показывать статистику',
    'settings.showStatsDesc': 'Отображать вашу статистику и активность другим пользователям',
    'settings.participateRanking': 'Участвовать в рейтинге',
    'settings.participateRankingDesc': 'Ваши оценки учитываются в общем рейтинге студентов',
    // Оценки (преподаватель)
    'settings.ratingsEnabled': 'Принимать оценки от студентов',
    'settings.ratingsEnabledDesc': 'Студенты могут ставить оценки и оставлять отзывы',
    'settings.ratingsEnabledOn': 'Оценивание включено',
    'settings.ratingsEnabledOff': 'Оценивание отключено',
    'settings.ratingsWarning': 'При отключении студенты не смогут оставить новые оценки. Ранее поставленные оценки сохранятся.',
    'settings.participateOverall': 'Участвовать в общем рейтинге',
    'settings.participateOverallDesc': 'Ваш рейтинг отображается в общем списке преподавателей на странице «Преподаватели»',
    // Безопасность
    'settings.changePassword': 'Сменить пароль',
    'settings.changePasswordDesc': 'Отправим письмо со ссылкой для смены пароля на ваш email',
    'settings.sendResetEmail': 'Отправить письмо',
    'settings.resetEmailSent': 'Письмо отправлено! Проверьте почту.',
    'settings.loginAs': 'Вы вошли как',
    'settings.twoFactor': 'Двухфакторная аутентификация',
    'settings.twoFactorDesc': 'Дополнительная защита аккаунта (скоро)',
    // Аккаунт
    'settings.logoutBtn': 'Выйти из аккаунта',
    'settings.dangerZone': 'Опасная зона',
    'settings.deleteAccount': 'Удалить аккаунт',
    'settings.deleteAccountDesc': 'Это действие необратимо. Все данные будут удалены.',
    // ── Страница входа ──
    'login.title': 'Войдите в свой аккаунт',
    'login.resetTitle': 'Восстановление пароля',
    'login.resetDesc': 'Введите email, на который зарегистрирован аккаунт. Мы отправим ссылку для сброса пароля.',
    'login.sendLink': 'Отправить ссылку',
    'login.sending': 'Отправка...',
    'login.backToLogin': 'Вернуться к входу',
    'login.password': 'Пароль',
    'login.passwordPlaceholder': 'Введите пароль',
    'login.forgotPassword': 'Забыли пароль?',
    'login.signingIn': 'Вход...',
    'login.signIn': 'Войти',
    'login.noAccount': 'Ещё нет аккаунта?',
    'login.registerLink': 'Зарегистрируйтесь',
    'login.welcome': 'Добро пожаловать!',
    'login.resetSent': 'Письмо для сброса пароля отправлено!',
    // ── Страница регистрации ──
    'reg.title': 'Регистрация',
    'reg.chooseRole': 'Выберите вашу роль',
    'reg.student': 'Я студент',
    'reg.studentDesc': 'Доступ к материалам и оценке преподавателей',
    'reg.teacher': 'Я преподаватель',
    'reg.teacherDesc': 'Загрузка материалов и управление профилем',
    'reg.haveAccount': 'Уже есть аккаунт?',
    'reg.signIn': 'Войдите',
    'reg.studentTitle': 'Регистрация студента',
    'reg.teacherTitle': 'Заявка преподавателя',
    'reg.firstName': 'Имя',
    'reg.lastName': 'Фамилия',
    'reg.middleName': 'Отчество',
    'reg.password': 'Пароль',
    'reg.passwordPlaceholder': 'Минимум 6 символов',
    'reg.confirmPassword': 'Повторите пароль',
    'reg.confirmPlaceholder': 'Введите пароль ещё раз',
    'reg.course': 'Курс',
    'reg.position': 'Должность',
    'reg.disciplines': 'Преподаваемые дисциплины',
    'reg.disciplinePlaceholder': 'Введите дисциплину и нажмите +',
    'reg.teachingType': 'Тип преподавания',
    'reg.agree': 'Я согласен с правилами использования портала',
    'reg.teacherNote': 'Ваш аккаунт будет активирован администратором в течение 24 часов',
    'reg.back': 'Назад',
    'reg.registering': 'Регистрация...',
    'reg.submit': 'Подать заявку',
    'reg.register': 'Зарегистрироваться',
    'reg.successStudent': 'Регистрация прошла успешно!',
    'reg.successTeacher': 'Заявка отправлена! Ожидайте активации администратором.',
    // ── Подвал ──
    'footer.desc': 'Рейтинги преподавателей, учебные материалы и личный кабинет — всё в одном месте',
    'footer.nav': 'Навигация',
    'footer.contacts': 'Контакты',
    'footer.copyright': 'Студенческий портал',
    // ── Карточка материала ──
    'mat.download': 'Скачать',
    'mat.allCourses': 'Все курсы',
    // ── Модальное окно оценки ──
    'rm.title': 'Оценить преподавателя',
    'rm.avgScore': 'Ваша средняя оценка',
    'rm.comment': 'Комментарий',
    'rm.commentPlaceholder': 'Опишите ваш опыт. Минимум 30 символов. Будьте объективны и конкретны.',
    'rm.warning': 'Ваш комментарий будет опубликован только после проверки администрацией',
    'rm.cancel': 'Отмена',
    'rm.submit': 'Отправить на модерацию',
    'rm.submitting': 'Отправка...',
    'rm.successTitle': 'Ваша оценка принята!',
    'rm.successDesc': 'Комментарий будет опубликован после проверки администрацией',
    'rm.close': 'Закрыть',
    'rm.allCriteria': 'Оцените все критерии',
    'rm.commentMin': 'Комментарий должен содержать минимум 30 символов',
    // ── Загрузка материала ──
    'up.title': 'Загрузка материала',
    'up.subtitle': 'Заполните информацию и прикрепите файл',
    'up.materialTitle': 'Название материала',
    'up.discipline': 'Дисциплина',
    'up.category': 'Категория',
    'up.chooseCategory': 'Выберите категорию',
    'up.courses': 'Для каких курсов',
    'up.allCourses': 'Все курсы',
    'up.description': 'Описание (необязательно)',
    'up.file': 'Файл',
    'up.dropzone': 'Перетащите файл сюда или нажмите для выбора',
    'up.dropzoneHint': 'PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX. Максимум 50 МБ',
    'up.uploading': 'Загрузка файла...',
    'up.cancel': 'Отмена',
    'up.publish': 'Опубликовать',
    'up.loading': 'Загрузка...',
    'up.noFile': 'Выберите файл для загрузки',
    'up.noCourse': 'Выберите для каких курсов материал',
    'up.success': 'Материал успешно опубликован!',
    'up.invalidFile': 'Неподдерживаемый формат. Допустимые: PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX',
    'up.fileTooLarge': 'Файл слишком большой. Максимум 50 МБ',
    // ── Навигация (доп.) ──
    'nav.logoutSuccess': 'Вы вышли из аккаунта',
    // ── Общие ──
    'common.loading': 'Загрузка...',
    'common.year': 'курс',
    'common.notSpecified': 'Не указано',
    'common.deleteConfirm': 'Удалить',
  },

  en: {
    'nav.home': 'Home',
    'nav.materials': 'Materials',
    'nav.teachers': 'Teachers',
    'nav.login': 'Sign In',
    'nav.register': 'Sign Up',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    'home.heroTitle1': 'Everything for studying —',
    'home.heroTitle2': 'in one place',
    'home.heroSubtitle': 'Teacher ratings, study materials and your personal dashboard — all in one portal for students and educators',
    'home.heroBtn': 'Enter portal',
    'home.learnMore': 'Learn more',
    'home.featuresTitle': 'What EduHub offers',
    'home.featuresSubtitle': 'EduHub brings together everything you need for studying and teaching',
    'home.materialsTitle': 'Recent materials',
    'home.materialsAll': 'View all',
    'home.ctaTitle': 'Join EduHub',
    'home.ctaDesc': 'Create an account and access teacher ratings, study materials and your personal dashboard',
    'home.ctaRegister': 'Register',
    'home.ctaTeachers': 'Teachers',
    'stat.students': 'Students',
    'stat.teachers': 'Teachers',
    'stat.materials': 'Materials',
    'stat.ratings': 'Ratings',
    'feat.materials': 'Study Materials',
    'feat.materialsDesc': 'Handouts, lectures and references — always at hand',
    'feat.rating': 'Teacher Ratings',
    'feat.ratingDesc': 'Honest student reviews based on transparent criteria',
    'feat.profile': 'Personal Dashboard',
    'feat.profileDesc': 'Your profile, bookmarks and rating history',
    'feat.moderation': 'Reliable Moderation',
    'feat.moderationDesc': 'All reviews are verified before publication',
    'teachers.title': 'Teachers',
    'teachers.subtitle': 'Ratings and profiles of university teachers',
    'teachers.search': 'Search by name or discipline...',
    'teachers.empty': 'No teachers found',
    'teachers.emptyHint': 'Try changing filters or clearing your search',
    'type.all': 'All',
    'type.lecturer': 'Lecturers',
    'type.practice': 'Practice',
    'type.seminar': 'Seminars',
    'type.supervisor': 'Supervisors',
    'type.universal': 'Universal',
    'typeBadge.lecturer': 'Lecturer',
    'typeBadge.practice': 'Practice',
    'typeBadge.seminar': 'Seminar',
    'typeBadge.supervisor': 'Supervisor',
    'typeBadge.universal': 'Universal',
    'tp.about': 'About',
    'tp.criteria': 'Rating Criteria',
    'tp.materials': 'Materials',
    'tp.reviews': 'Reviews',
    'tp.bio': 'About me',
    'tp.disciplines': 'Taught disciplines',
    'tp.contacts': 'Contacts',
    'tp.noInfo': 'This teacher has not filled in their profile yet',
    'tp.rateBtn': 'Rate this teacher',
    'tp.alreadyRated': 'You have already rated this teacher',
    'tp.noRatings': 'No approved ratings yet',
    'tp.noMaterials': 'No materials uploaded yet',
    'tp.noReviews': 'No approved reviews yet',
    'tp.criteriaAvg': 'Average ratings by criteria',
    'tp.notFound': 'Teacher not found',
    'tp.ratingBased': 'based on',
    'tp.ratingCount1': 'rating',
    'tp.ratingCountN': 'ratings',
    'tp.studentYear': 'Year',
    'tp.course': 'student',
    'mat.title': 'Study Materials',
    'mat.subtitle': 'Handouts, lectures, assignments and other files',
    'mat.upload': 'Upload',
    'mat.search': 'Search by title or discipline...',
    'mat.allCategories': 'All categories',
    'mat.allDisciplines': 'All disciplines',
    'mat.sortNewest': 'Newest first',
    'mat.sortAlphabet': 'Alphabetical',
    'mat.sortPopular': 'Most popular',
    'mat.empty': 'No materials found',
    'mat.emptyHint': 'Try changing filters or clearing your search',
    'mat.resetFilters': 'Reset filters',
    'mat.loadMore': 'Load more',
    'cat.all': 'All categories',
    'cat.methodical': 'Handout',
    'cat.lecture': 'Lecture',
    'cat.reference': 'Reference',
    'cat.assignment': 'Assignment',
    'cat.other': 'Other',
    'course.all': 'All years',
    'course.1': 'Year 1',
    'course.2': 'Year 2',
    'course.3': 'Year 3',
    'course.4': 'Year 4',
    'course.common': 'General',
    'td.myMaterials': 'My Materials',
    'td.ratings': 'Ratings & Reviews',
    'td.uploadBtn': 'Upload material',
    'td.uploadFirst': 'Upload your first material',
    'td.noMaterials': 'You have not uploaded any materials yet',
    'td.downloads': 'downloads',
    'td.ratingsToggleTitle': 'Allow students to rate',
    'td.ratingsOnDesc': 'Students can leave ratings and reviews',
    'td.ratingsOffDesc': 'Ratings disabled — students cannot leave reviews',
    'td.ratingsOn': 'Ratings enabled',
    'td.ratingsOff': 'Ratings disabled',
    'td.avgCriteria': 'Average ratings by criteria',
    'td.approved': 'Approved',
    'td.pending': 'Pending review',
    'td.rejected': 'Rejected',
    'td.studentReviews': 'Student reviews',
    'td.noReviews': 'No approved reviews yet',
    'td.statMaterials': 'Materials',
    'td.statRatings': 'Ratings',
    'td.statAvg': 'Average score',
    'td.studentYear': 'year',
    'td.studentPrefix': 'Year',
    'sp.myRatings': 'My Ratings',
    'sp.bookmarks': 'Bookmarks',
    'sp.noRatings': 'You have not rated any teachers yet',
    'sp.noBookmarks': 'You have no saved materials yet',
    'sp.statusPending': 'Under review',
    'sp.statusApproved': 'Approved',
    'sp.statusRejected': 'Rejected',
    'sp.statRatings': 'Ratings',
    'sp.statBookmarks': 'Bookmarks',
    'sp.role': 'Student',
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.ratings': 'Ratings',
    'settings.security': 'Security',
    'settings.account': 'Account',
    'settings.avatar': 'Avatar',
    'settings.avatarChange': 'Change avatar',
    'settings.avatarRemove': 'Remove',
    'settings.firstName': 'First name',
    'settings.lastName': 'Last name',
    'settings.middleName': 'Patronymic / Middle name',
    'settings.email': 'Email',
    'settings.phone': 'Phone',
    'settings.bio': 'About me',
    'settings.socialLinks': 'Social media',
    'settings.vk': 'VKontakte (link)',
    'settings.telegram': 'Telegram (username)',
    'settings.save': 'Save changes',
    'settings.saving': 'Saving...',
    'settings.course': 'Year',
    'settings.specialty': 'Major / Specialty',
    'settings.group': 'Study group',
    'settings.interests': 'Interests',
    'settings.goals': 'Learning goals',
    'settings.contactEmail': 'Contact email',
    'settings.degree': 'Academic degree',
    'settings.academicTitle': 'Academic title',
    'settings.department': 'Department',
    'settings.experience': 'Years of experience',
    'settings.researchInterests': 'Research interests',
    'settings.office': 'Office room',
    'settings.officeHours': 'Office hours',
    'settings.website': 'Personal website',
    'settings.degreeNone': 'No degree',
    'settings.degreeCandidate': 'Candidate of Sciences',
    'settings.degreeDoctor': 'Doctor of Sciences',
    'settings.titleNone': 'No title',
    'settings.titleAssistant': 'Assistant',
    'settings.titleDocent': 'Associate Professor',
    'settings.titleProfessor': 'Professor',
    'settings.theme': 'Theme',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.themeSystem': 'System',
    'settings.language': 'Interface language',
    'settings.fontSize': 'Text size',
    'settings.fontSizeNormal': 'Normal',
    'settings.fontSizeLarge': 'Large',
    'settings.fontSizeXLarge': 'Extra large',
    'settings.compactMode': 'Compact mode',
    'settings.compactModeDesc': 'Reduce spacing and element sizes for a denser layout',
    'settings.cardStyle': 'Card style',
    'settings.cardStyleElevated': 'Elevated',
    'settings.cardStyleFlat': 'Flat',
    'settings.cardStyleOutlined': 'Outlined',
    'settings.notifEmail': 'Email notifications',
    'settings.notifEmailDesc': 'Receive emails about new ratings and materials',
    'settings.notifRatings': 'New ratings',
    'settings.notifRatingsDesc': 'Notify when a student rates you',
    'settings.notifMaterials': 'New materials',
    'settings.notifMaterialsDesc': 'Notify about newly uploaded materials',
    'settings.notifMessages': 'Messages',
    'settings.notifMessagesDesc': 'Notifications about new incoming messages',
    'settings.notifAnnouncements': 'Announcements',
    'settings.notifAnnouncementsDesc': 'Important portal news and updates',
    'settings.notifDigest': 'Weekly digest',
    'settings.notifDigestDesc': 'Summary of events from the past week',
    'settings.profilePublic': 'Public profile',
    'settings.profilePublicDesc': 'Other users can view your profile',
    'settings.showEmail': 'Show email',
    'settings.showEmailDesc': 'Display email on public profile',
    'settings.showPhone': 'Show phone',
    'settings.showPhoneDesc': 'Display phone on public profile',
    'settings.showSocialLinks': 'Show social links',
    'settings.showSocialLinksDesc': 'Display VKontakte and Telegram links',
    'settings.showStats': 'Show statistics',
    'settings.showStatsDesc': 'Display your activity statistics to other users',
    'settings.participateRanking': 'Participate in ranking',
    'settings.participateRankingDesc': 'Your ratings count in the overall student ranking',
    'settings.ratingsEnabled': 'Accept student ratings',
    'settings.ratingsEnabledDesc': 'Students can rate you and leave reviews',
    'settings.ratingsEnabledOn': 'Ratings enabled',
    'settings.ratingsEnabledOff': 'Ratings disabled',
    'settings.ratingsWarning': 'When disabled, students cannot leave new ratings. Existing ratings are preserved.',
    'settings.participateOverall': 'Participate in overall ranking',
    'settings.participateOverallDesc': 'Your rating is displayed in the overall teacher list on the Teachers page',
    'settings.changePassword': 'Change password',
    'settings.changePasswordDesc': "We'll send a password reset link to your email",
    'settings.sendResetEmail': 'Send email',
    'settings.resetEmailSent': 'Email sent! Check your inbox.',
    'settings.loginAs': 'Logged in as',
    'settings.twoFactor': 'Two-factor authentication',
    'settings.twoFactorDesc': 'Enhanced account security (coming soon)',
    'settings.logoutBtn': 'Log out',
    'settings.dangerZone': 'Danger zone',
    'settings.deleteAccount': 'Delete account',
    'settings.deleteAccountDesc': 'This action is irreversible. All data will be deleted.',
    'login.title': 'Sign in to your account',
    'login.resetTitle': 'Password recovery',
    'login.resetDesc': 'Enter the email associated with your account. We will send a reset link.',
    'login.sendLink': 'Send link',
    'login.sending': 'Sending...',
    'login.backToLogin': 'Back to sign in',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.forgotPassword': 'Forgot password?',
    'login.signingIn': 'Signing in...',
    'login.signIn': 'Sign in',
    'login.noAccount': 'Don\'t have an account?',
    'login.registerLink': 'Sign up',
    'login.welcome': 'Welcome!',
    'login.resetSent': 'Password reset email sent!',
    'reg.title': 'Registration',
    'reg.chooseRole': 'Choose your role',
    'reg.student': 'I\'m a student',
    'reg.studentDesc': 'Access to materials and teacher ratings',
    'reg.teacher': 'I\'m a teacher',
    'reg.teacherDesc': 'Upload materials and manage your profile',
    'reg.haveAccount': 'Already have an account?',
    'reg.signIn': 'Sign in',
    'reg.studentTitle': 'Student registration',
    'reg.teacherTitle': 'Teacher application',
    'reg.firstName': 'First name',
    'reg.lastName': 'Last name',
    'reg.middleName': 'Patronymic',
    'reg.password': 'Password',
    'reg.passwordPlaceholder': 'At least 6 characters',
    'reg.confirmPassword': 'Confirm password',
    'reg.confirmPlaceholder': 'Enter password again',
    'reg.course': 'Year',
    'reg.position': 'Position',
    'reg.disciplines': 'Taught disciplines',
    'reg.disciplinePlaceholder': 'Enter a discipline and press +',
    'reg.teachingType': 'Teaching type',
    'reg.agree': 'I agree to the portal terms of use',
    'reg.teacherNote': 'Your account will be activated by an administrator within 24 hours',
    'reg.back': 'Back',
    'reg.registering': 'Registering...',
    'reg.submit': 'Submit application',
    'reg.register': 'Register',
    'reg.successStudent': 'Registration successful!',
    'reg.successTeacher': 'Application submitted! Await administrator activation.',
    'footer.desc': 'Teacher ratings, study materials and personal dashboard — all in one place',
    'footer.nav': 'Navigation',
    'footer.contacts': 'Contacts',
    'footer.copyright': 'Student portal',
    'mat.download': 'Download',
    'mat.allCourses': 'All years',
    'rm.title': 'Rate this teacher',
    'rm.avgScore': 'Your average score',
    'rm.comment': 'Comment',
    'rm.commentPlaceholder': 'Describe your experience. At least 30 characters. Be objective and specific.',
    'rm.warning': 'Your comment will only be published after verification by the administration',
    'rm.cancel': 'Cancel',
    'rm.submit': 'Submit for moderation',
    'rm.submitting': 'Submitting...',
    'rm.successTitle': 'Your rating has been submitted!',
    'rm.successDesc': 'The comment will be published after review by the administration',
    'rm.close': 'Close',
    'rm.allCriteria': 'Please rate all criteria',
    'rm.commentMin': 'Comment must be at least 30 characters',
    'up.title': 'Upload material',
    'up.subtitle': 'Fill in the information and attach a file',
    'up.materialTitle': 'Material title',
    'up.discipline': 'Discipline',
    'up.category': 'Category',
    'up.chooseCategory': 'Choose a category',
    'up.courses': 'For which years',
    'up.allCourses': 'All years',
    'up.description': 'Description (optional)',
    'up.file': 'File',
    'up.dropzone': 'Drop a file here or click to select',
    'up.dropzoneHint': 'PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX. Maximum 50 MB',
    'up.uploading': 'Uploading file...',
    'up.cancel': 'Cancel',
    'up.publish': 'Publish',
    'up.loading': 'Loading...',
    'up.noFile': 'Please select a file to upload',
    'up.noCourse': 'Please select which years this material is for',
    'up.success': 'Material published successfully!',
    'up.invalidFile': 'Unsupported format. Allowed: PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX',
    'up.fileTooLarge': 'File is too large. Maximum 50 MB',
    'nav.logoutSuccess': 'You have been signed out',
    'common.loading': 'Loading...',
    'common.year': 'year',
    'common.notSpecified': 'Not specified',
    'common.deleteConfirm': 'Delete',
  },

  zh: {
    'nav.home': '首页',
    'nav.materials': '资料',
    'nav.teachers': '教师',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.dashboard': '个人中心',
    'nav.settings': '设置',
    'nav.logout': '退出',
    'home.heroTitle1': '学习所需——',
    'home.heroTitle2': '尽在一处',
    'home.heroSubtitle': '教师评分、学习资料和个人中心——专为学生和教师打造的一体化平台',
    'home.heroBtn': '进入平台',
    'home.learnMore': '了解更多',
    'home.featuresTitle': '平台功能',
    'home.featuresSubtitle': 'EduHub 将学习与教学所需的一切整合在一起',
    'home.materialsTitle': '最新资料',
    'home.materialsAll': '查看全部',
    'home.ctaTitle': '加入 EduHub',
    'home.ctaDesc': '注册账号，访问教师评分、学习资料和个人中心',
    'home.ctaRegister': '立即注册',
    'home.ctaTeachers': '教师列表',
    'stat.students': '学生',
    'stat.teachers': '教师',
    'stat.materials': '资料',
    'stat.ratings': '评分',
    'feat.materials': '学习资料',
    'feat.materialsDesc': '讲义、讲座和参考资料——随时可用',
    'feat.rating': '教师评分',
    'feat.ratingDesc': '基于透明标准的学生真实评价',
    'feat.profile': '个人中心',
    'feat.profileDesc': '个人资料、书签和评分历史',
    'feat.moderation': '可靠审核',
    'feat.moderationDesc': '所有评价在发布前均经过审核',
    'teachers.title': '教师',
    'teachers.subtitle': '大学教师的评分与简介',
    'teachers.search': '按姓名或课程搜索...',
    'teachers.empty': '未找到教师',
    'teachers.emptyHint': '请尝试更改筛选条件或清除搜索',
    'type.all': '全部',
    'type.lecturer': '讲师',
    'type.practice': '实践课',
    'type.seminar': '研讨课',
    'type.supervisor': '导师',
    'type.universal': '通用型',
    'typeBadge.lecturer': '讲师',
    'typeBadge.practice': '实践',
    'typeBadge.seminar': '研讨',
    'typeBadge.supervisor': '导师',
    'typeBadge.universal': '通用型',
    'tp.about': '关于作者',
    'tp.criteria': '评分标准',
    'tp.materials': '资料',
    'tp.reviews': '评价',
    'tp.bio': '自我介绍',
    'tp.disciplines': '教授课程',
    'tp.contacts': '联系方式',
    'tp.noInfo': '该教师尚未填写个人信息',
    'tp.rateBtn': '评价此教师',
    'tp.alreadyRated': '您已评价过该教师',
    'tp.noRatings': '暂无已审核的评分',
    'tp.noMaterials': '该教师尚未上传资料',
    'tp.noReviews': '暂无已审核的评价',
    'tp.criteriaAvg': '各标准平均评分',
    'tp.notFound': '未找到该教师',
    'tp.ratingBased': '基于',
    'tp.ratingCount1': '条评分',
    'tp.ratingCountN': '条评分',
    'tp.studentYear': '年级',
    'tp.course': '学生',
    'mat.title': '学习资料',
    'mat.subtitle': '讲义、讲座、作业及其他文件',
    'mat.upload': '上传',
    'mat.search': '按标题或课程搜索...',
    'mat.allCategories': '所有类别',
    'mat.allDisciplines': '所有课程',
    'mat.sortNewest': '最新优先',
    'mat.sortAlphabet': '按字母排序',
    'mat.sortPopular': '最受欢迎',
    'mat.empty': '未找到资料',
    'mat.emptyHint': '请尝试更改筛选条件或清除搜索',
    'mat.resetFilters': '重置筛选',
    'mat.loadMore': '加载更多',
    'cat.all': '所有类别',
    'cat.methodical': '讲义',
    'cat.lecture': '讲座',
    'cat.reference': '参考资料',
    'cat.assignment': '作业',
    'cat.other': '其他',
    'course.all': '所有年级',
    'course.1': '一年级',
    'course.2': '二年级',
    'course.3': '三年级',
    'course.4': '四年级',
    'course.common': '通用',
    'td.myMaterials': '我的资料',
    'td.ratings': '评分与评价',
    'td.uploadBtn': '上传资料',
    'td.uploadFirst': '上传第一份资料',
    'td.noMaterials': '您尚未上传任何资料',
    'td.downloads': '次下载',
    'td.ratingsToggleTitle': '允许学生评分',
    'td.ratingsOnDesc': '学生可以留下评分和评价',
    'td.ratingsOffDesc': '评分已关闭——学生无法留下评价',
    'td.ratingsOn': '评分已启用',
    'td.ratingsOff': '评分已停用',
    'td.avgCriteria': '各标准平均评分',
    'td.approved': '已审核',
    'td.pending': '审核中',
    'td.rejected': '已拒绝',
    'td.studentReviews': '学生评价',
    'td.noReviews': '暂无已审核的评价',
    'td.statMaterials': '资料',
    'td.statRatings': '评分',
    'td.statAvg': '平均分',
    'td.studentYear': '年级',
    'td.studentPrefix': '第',
    'sp.myRatings': '我的评分',
    'sp.bookmarks': '书签',
    'sp.noRatings': '您尚未评价任何教师',
    'sp.noBookmarks': '您尚无保存的资料',
    'sp.statusPending': '审核中',
    'sp.statusApproved': '已审核',
    'sp.statusRejected': '已拒绝',
    'sp.statRatings': '评分',
    'sp.statBookmarks': '书签',
    'sp.role': '学生',
    'settings.title': '设置',
    'settings.profile': '个人资料',
    'settings.appearance': '外观',
    'settings.notifications': '通知',
    'settings.privacy': '隐私',
    'settings.ratings': '评分',
    'settings.security': '安全',
    'settings.account': '账户',
    'settings.avatar': '头像',
    'settings.avatarChange': '更改头像',
    'settings.avatarRemove': '删除',
    'settings.firstName': '名',
    'settings.lastName': '姓',
    'settings.middleName': '父称/中间名',
    'settings.email': '邮箱',
    'settings.phone': '电话',
    'settings.bio': '关于我',
    'settings.socialLinks': '社交媒体',
    'settings.vk': 'VKontakte（链接）',
    'settings.telegram': 'Telegram（用户名）',
    'settings.save': '保存更改',
    'settings.saving': '保存中...',
    'settings.course': '年级',
    'settings.specialty': '专业',
    'settings.group': '学习小组',
    'settings.interests': '兴趣',
    'settings.goals': '学习目标',
    'settings.contactEmail': '联系邮箱',
    'settings.degree': '学位',
    'settings.academicTitle': '学术职称',
    'settings.department': '院系',
    'settings.experience': '工作年限',
    'settings.researchInterests': '研究方向',
    'settings.office': '办公室号',
    'settings.officeHours': '接待时间',
    'settings.website': '个人网站',
    'settings.degreeNone': '无学位',
    'settings.degreeCandidate': '副博士',
    'settings.degreeDoctor': '博士',
    'settings.titleNone': '无职称',
    'settings.titleAssistant': '助教',
    'settings.titleDocent': '副教授',
    'settings.titleProfessor': '教授',
    'settings.theme': '主题',
    'settings.themeLight': '浅色',
    'settings.themeDark': '深色',
    'settings.themeSystem': '跟随系统',
    'settings.language': '界面语言',
    'settings.fontSize': '文字大小',
    'settings.fontSizeNormal': '普通',
    'settings.fontSizeLarge': '大',
    'settings.fontSizeXLarge': '特大',
    'settings.compactMode': '紧凑模式',
    'settings.compactModeDesc': '减少间距和元素大小以获得更密集的布局',
    'settings.cardStyle': '卡片风格',
    'settings.cardStyleElevated': '立体',
    'settings.cardStyleFlat': '扁平',
    'settings.cardStyleOutlined': '描边',
    'settings.notifEmail': '邮件通知',
    'settings.notifEmailDesc': '接收关于新评分和资料的邮件',
    'settings.notifRatings': '新评分',
    'settings.notifRatingsDesc': '当学生评价您时通知',
    'settings.notifMaterials': '新资料',
    'settings.notifMaterialsDesc': '通知新上传的资料',
    'settings.notifMessages': '消息',
    'settings.notifMessagesDesc': '新消息通知',
    'settings.notifAnnouncements': '公告',
    'settings.notifAnnouncementsDesc': '重要门户新闻和更新',
    'settings.notifDigest': '每周摘要',
    'settings.notifDigestDesc': '过去一周的事件汇总',
    'settings.profilePublic': '公开资料',
    'settings.profilePublicDesc': '其他用户可以查看您的个人资料',
    'settings.showEmail': '显示邮箱',
    'settings.showEmailDesc': '在公开资料中显示邮箱',
    'settings.showPhone': '显示电话',
    'settings.showPhoneDesc': '在公开资料中显示电话',
    'settings.showSocialLinks': '显示社交链接',
    'settings.showSocialLinksDesc': '显示VKontakte和Telegram链接',
    'settings.showStats': '显示统计',
    'settings.showStatsDesc': '向其他用户显示您的活动统计',
    'settings.participateRanking': '参与排行',
    'settings.participateRankingDesc': '您的评分计入学生总排行',
    'settings.ratingsEnabled': '接受学生评分',
    'settings.ratingsEnabledDesc': '学生可以对您评分并留下评论',
    'settings.ratingsEnabledOn': '评分已启用',
    'settings.ratingsEnabledOff': '评分已停用',
    'settings.ratingsWarning': '停用后，学生将无法留下新评分。已有评分将保留。',
    'settings.participateOverall': '参与总排行',
    'settings.participateOverallDesc': '您的评分显示在「教师」页面的总列表中',
    'settings.changePassword': '修改密码',
    'settings.changePasswordDesc': '我们将向您的邮箱发送密码重置链接',
    'settings.sendResetEmail': '发送邮件',
    'settings.resetEmailSent': '邮件已发送！请检查您的收件箱。',
    'settings.loginAs': '当前登录',
    'settings.twoFactor': '双因素认证',
    'settings.twoFactorDesc': '增强账户安全性（即将推出）',
    'settings.logoutBtn': '退出登录',
    'settings.dangerZone': '危险操作',
    'settings.deleteAccount': '删除账户',
    'settings.deleteAccountDesc': '此操作不可逆，所有数据将被删除。',
    'login.title': '登录您的账号',
    'login.resetTitle': '找回密码',
    'login.resetDesc': '请输入注册时使用的邮箱地址，我们将发送重置密码链接。',
    'login.sendLink': '发送链接',
    'login.sending': '发送中...',
    'login.backToLogin': '返回登录',
    'login.password': '密码',
    'login.passwordPlaceholder': '请输入密码',
    'login.forgotPassword': '忘记密码？',
    'login.signingIn': '登录中...',
    'login.signIn': '登录',
    'login.noAccount': '还没有账号？',
    'login.registerLink': '立即注册',
    'login.welcome': '欢迎！',
    'login.resetSent': '密码重置邮件已发送！',
    'reg.title': '注册',
    'reg.chooseRole': '选择您的角色',
    'reg.student': '我是学生',
    'reg.studentDesc': '访问资料和教师评分',
    'reg.teacher': '我是教师',
    'reg.teacherDesc': '上传资料并管理个人资料',
    'reg.haveAccount': '已有账号？',
    'reg.signIn': '登录',
    'reg.studentTitle': '学生注册',
    'reg.teacherTitle': '教师申请',
    'reg.firstName': '名',
    'reg.lastName': '姓',
    'reg.middleName': '父称',
    'reg.password': '密码',
    'reg.passwordPlaceholder': '至少6个字符',
    'reg.confirmPassword': '确认密码',
    'reg.confirmPlaceholder': '再次输入密码',
    'reg.course': '年级',
    'reg.position': '职位',
    'reg.disciplines': '教授课程',
    'reg.disciplinePlaceholder': '输入课程名称并按+',
    'reg.teachingType': '教学类型',
    'reg.agree': '我同意平台使用条款',
    'reg.teacherNote': '您的账号将在24小时内由管理员激活',
    'reg.back': '返回',
    'reg.registering': '注册中...',
    'reg.submit': '提交申请',
    'reg.register': '注册',
    'reg.successStudent': '注册成功！',
    'reg.successTeacher': '申请已提交！请等待管理员激活。',
    'footer.desc': '教师评分、学习资料和个人中心——尽在一处',
    'footer.nav': '导航',
    'footer.contacts': '联系方式',
    'footer.copyright': '学生门户',
    'mat.download': '下载',
    'mat.allCourses': '所有年级',
    'rm.title': '评价此教师',
    'rm.avgScore': '您的平均分',
    'rm.comment': '评论',
    'rm.commentPlaceholder': '描述您的经历。至少30个字符。请客观具体。',
    'rm.warning': '您的评论仅在管理员审核后才会发布',
    'rm.cancel': '取消',
    'rm.submit': '提交审核',
    'rm.submitting': '提交中...',
    'rm.successTitle': '您的评分已提交！',
    'rm.successDesc': '评论将在管理员审核后发布',
    'rm.close': '关闭',
    'rm.allCriteria': '请对所有标准评分',
    'rm.commentMin': '评论至少需要30个字符',
    'up.title': '上传资料',
    'up.subtitle': '填写信息并附上文件',
    'up.materialTitle': '资料标题',
    'up.discipline': '课程',
    'up.category': '类别',
    'up.chooseCategory': '选择类别',
    'up.courses': '适用年级',
    'up.allCourses': '所有年级',
    'up.description': '描述（可选）',
    'up.file': '文件',
    'up.dropzone': '将文件拖放到此处或点击选择',
    'up.dropzoneHint': 'PDF、DOC、DOCX、PPT、PPTX、XLS、XLSX。最大50 MB',
    'up.uploading': '上传文件中...',
    'up.cancel': '取消',
    'up.publish': '发布',
    'up.loading': '加载中...',
    'up.noFile': '请选择要上传的文件',
    'up.noCourse': '请选择适用的年级',
    'up.success': '资料发布成功！',
    'up.invalidFile': '不支持的格式。允许：PDF、DOC、DOCX、PPT、PPTX、XLS、XLSX',
    'up.fileTooLarge': '文件过大。最大50 MB',
    'nav.logoutSuccess': '您已退出登录',
    'common.loading': '加载中...',
    'common.year': '年级',
    'common.notSpecified': '未填写',
    'common.deleteConfirm': '删除',
  },
}

function getSystemTheme() {
  if (typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    return 'dark'
  }
  return 'light'
}

export function SettingsProvider({ children }) {
  const [themeMode, setThemeMode] = useState(() => localStorage.getItem('eduhub_theme') || 'light')
  const [language, setLanguage] = useState(() => localStorage.getItem('eduhub_lang') || 'ru')
  const [fontSize, setFontSize] = useState(() => localStorage.getItem('eduhub_fontsize') || 'normal')
  const [compactMode, setCompactMode] = useState(() => localStorage.getItem('eduhub_compact') === 'true')
  const [cardStyle, setCardStyle] = useState(() => localStorage.getItem('eduhub_cardstyle') || 'elevated')

  const [notifications, setNotifications] = useState(() => {
    const saved = localStorage.getItem('eduhub_notif')
    return saved ? JSON.parse(saved) : { email: true, ratings: true, materials: true, messages: true, announcements: true, digest: false }
  })

  const [privacy, setPrivacy] = useState(() => {
    const saved = localStorage.getItem('eduhub_privacy')
    return saved ? JSON.parse(saved) : { profilePublic: true, showEmail: false, showPhone: false, showSocialLinks: true, showStats: true, participateRanking: true }
  })

  useEffect(() => {
    const effectiveTheme = themeMode === 'system' ? getSystemTheme() : themeMode
    document.documentElement.classList.toggle('dark', effectiveTheme === 'dark')
    localStorage.setItem('eduhub_theme', themeMode)
  }, [themeMode])

  useEffect(() => {
    document.documentElement.lang = language
    localStorage.setItem('eduhub_lang', language)
  }, [language])

  useEffect(() => {
    const sizeMap = { normal: '16px', large: '17.5px', xlarge: '19px' }
    document.documentElement.style.fontSize = sizeMap[fontSize] || '16px'
    localStorage.setItem('eduhub_fontsize', fontSize)
  }, [fontSize])

  useEffect(() => {
    document.documentElement.classList.toggle('compact', compactMode)
    localStorage.setItem('eduhub_compact', String(compactMode))
  }, [compactMode])

  useEffect(() => {
    document.documentElement.setAttribute('data-cardstyle', cardStyle)
    localStorage.setItem('eduhub_cardstyle', cardStyle)
  }, [cardStyle])

  useEffect(() => {
    localStorage.setItem('eduhub_notif', JSON.stringify(notifications))
  }, [notifications])

  useEffect(() => {
    localStorage.setItem('eduhub_privacy', JSON.stringify(privacy))
  }, [privacy])

  useEffect(() => {
    if (themeMode !== 'system') return
    const mq = window.matchMedia('(prefers-color-scheme: dark)')
    const handler = () => document.documentElement.classList.toggle('dark', mq.matches)
    mq.addEventListener('change', handler)
    return () => mq.removeEventListener('change', handler)
  }, [themeMode])

  const t = (key) => TRANSLATIONS[language]?.[key] || TRANSLATIONS.ru[key] || key

  const value = {
    themeMode, setThemeMode,
    language, setLanguage,
    fontSize, setFontSize,
    compactMode, setCompactMode,
    cardStyle, setCardStyle,
    notifications, setNotifications,
    privacy, setPrivacy,
    t,
    languages: [
      { code: 'ru', label: 'Русский', flag: '🇷🇺' },
      { code: 'en', label: 'English', flag: '🇺🇸' },
      { code: 'zh', label: '中文', flag: '🇨🇳' },
    ],
  }

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>
}
